version: '3.1'
services:

  web:
    image: nemanja0505/probafirma10:patientwebappliacation_latest
    container_name: web
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: demo
      DATABASE_PASSWORD: demo
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes:
      - web:/app/sql

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: demo
      MYSQL_USER: demo
      MYSQL_DATABASE: MYSQLHealtcareDB
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  web:  

networks:
  demo:
    name: demo
    driver: bridge
    